version: "3.9"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - "ACCEPT_EULA=Y" 
      - "MSSQL_SA_PASSWORD=@1234567890Developer"

networks:
  sqlserver:
    name: sqlserver
